repos:
- repo: https://github.com/psf/black
  rev: 23.12.0
  hooks:
  - id: black
    files: ^flask-app/.*\.py$

- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    files: ^flask-app/.*\.py$
    args: ['--max-line-length=81']

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.6
  hooks:
  - id: bandit
    files: ^flask-app/.*\.py$
    exclude: '^flask-app/tests/'

- repo: https://github.com/terrencepreilly/darglint
  rev: v1.8.1
  hooks:
  - id: darglint
    files: ^flask-app/.*\.py$