name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  code_quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
  
    - name: Install dependencies
      run: |
        pipenv install --dev

    - name: Run linter
      run: |
        pipenv run flake8 --max-line-length=81

    - name: Run type checker (mypy)
      run: |
        pipenv run mypy .
  
    - name: Run code formatter (black)
      run: |
        pipenv run black --line-length=80 .
  
    - name: Run security linter (bandit)
      run: |
        pipenv run bandit -r . --exclude tests
  
    - name: Run import sorter (isort)
      run: |
        pipenv run isort .
  
    - name: Run tests with coverage (pytest-coverage)
      run: |
        pipenv run pytest --cov=.
